name: Flutter Web Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.31.0-0.1.pre'  # Ajusta a tu versión
          channel: 'beta'
      
      - name: Get dependencies
        run: flutter pub get
        
      - name: Enable web
        run: flutter config --enable-web
        
      - name: Clean before build
        run: flutter clean
        
      - name: Build web
        run: flutter build web --release --base-href '/flutter_to_sheets_new/'
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

